export type RootStackParams = {
  Main: undefined;
  Home: undefined;
  Init: undefined;
  Login: undefined;
  SignUp: undefined;
  Agreement: undefined;
  Record: undefined;
  SearchProfile: undefined;
  AddRoomCode: undefined;
  EnterRoom: undefined;
  AddRoomTitle: undefined;
  AddRoomInfo: { roomName: string };
  CompleteRoom: { roomCode: string };
  WaitingRoom: { roomId: number; username: string };
  RunningRoom: { roomId: number };
  ResultRoom: { roomId: number };
  RegisterStock: { stockName: string; roomId: number };
  SearchStock: { roomId: number };
  Mypage: undefined;
};
